pubsub_subscribe("CreateLocalControllableCharacter",EventControllableCharacterCreate);
pubsub_subscribe("EnableLocalInputListening",EventToggleInputListening);
pubsub_subscribe("DestroyLocalControllableCharacter",EventControllableCharacterDestroy);